async fn main() {
    break
    #! ERROR cannot `break` outside of a loop
    #! RUN ERROR compilation error encountered
}
